# Generated by Django 4.2.6 on 2023-10-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='dbendpoint',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='dbpass',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subscription_exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subscription_status',
            field=models.BooleanField(default=False, null=True, verbose_name='subscription_status'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='dbmodel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subscription_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
