# Generated by Django 4.2.6 on 2023-10-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscribers_dbendpoint_subscribers_dbpass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='dbendpoint',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='dbmodel',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='dbpass',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='subscription_customer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
